SCREEN_WIDTH = 1920
SCREEN_HEIGHT = 1080

TEXT_PADDING = 20

PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200
PLAYER_SHOOT_SPEED_BASE = 500
PLAYER_SHOOT_COOLDOWN_BASE = 0.15

SHOT_RADIUS = 5

POWERUP_RADIUS = 10
POWERUP_SPAWN_RATE = 10
POWERUP_KINDS = ("shot_rate", "shot_speed")