SCREEN_WIDTH = 1920
SCREEN_HEIGHT = 1080

TEXT_PADDING = 20
SPAWN_PADDING = 50

PLAYER_RADIUS = 15
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 300
PLAYER_SHOOT_SPEED_BASE = 400
PLAYER_SHOOT_COOLDOWN_BASE = 0.10

# UPGRADE_SPEED = PLAYER_SPEED // 2

ENEMY_GROUP_SPAWN_INTERVAL = 1
ENEMY_SPAWN_INTERVAL = 0.1
ENEMY_GROUP_SIZE = 10

BASIC_CIRCLE_ENEMY_RADIUS = 20
BASIC_CIRCLE_ENEMY_SPEED = 60
BASIC_CIRCLE_ENEMY_COLOR = (255,255,255)
BASIC_CIRCLE_ENEMY_SCORE = 10

SHOT_RADIUS = 5

POWERUP_RADIUS = 10
POWERUP_SPAWN_RATE = 10
POWERUP_KINDS = ("shot_rate", "shot_speed")